# Generated by Django 4.2.7 on 2023-12-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ememo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ememo',
            name='step',
            field=models.CharField(choices=[('Drafted', 'Drafted'), ('PRE_APPROVE', 'Pre Approve'), ('FINAL_APPROVE', 'Final Approve'), ('DONE', 'Done')], default='Drafted', max_length=13),
        ),
    ]
