# Generated by Django 4.2.7 on 2023-12-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ememo', '0003_alter_ememo_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ememo',
            name='step',
            field=models.CharField(choices=[('Drafted', 'Drafted'), ('PRE_APPROVE', 'PRE_APPROVE'), ('FINAL_APPROVE', 'FINAL_APPROVE'), ('DONE', 'Done')], default='Drafted', max_length=13),
        ),
        migrations.AlterField(
            model_name='flowememo',
            name='source',
            field=models.CharField(choices=[('Drafted', 'Drafted'), ('PRE_APPROVE', 'PRE_APPROVE'), ('FINAL_APPROVE', 'FINAL_APPROVE'), ('DONE', 'Done')], max_length=13),
        ),
        migrations.AlterField(
            model_name='flowememo',
            name='target',
            field=models.CharField(choices=[('Drafted', 'Drafted'), ('PRE_APPROVE', 'PRE_APPROVE'), ('FINAL_APPROVE', 'FINAL_APPROVE'), ('DONE', 'Done')], max_length=13),
        ),
        migrations.AlterField(
            model_name='logememo',
            name='source',
            field=models.CharField(choices=[('Drafted', 'Drafted'), ('PRE_APPROVE', 'PRE_APPROVE'), ('FINAL_APPROVE', 'FINAL_APPROVE'), ('DONE', 'Done')], max_length=13),
        ),
        migrations.AlterField(
            model_name='logememo',
            name='target',
            field=models.CharField(choices=[('Drafted', 'Drafted'), ('PRE_APPROVE', 'PRE_APPROVE'), ('FINAL_APPROVE', 'FINAL_APPROVE'), ('DONE', 'Done')], max_length=13),
        ),
    ]
