# Generated by Django 4.2.7 on 2023-12-08 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ememo', '0004_alter_ememo_step_alter_flowememo_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ememo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ememo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
