# Generated by Django 4.2.7 on 2023-12-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ememo', '0007_flowememo_assign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowememo',
            name='assign',
        ),
        migrations.AddField(
            model_name='flowememo',
            name='step',
            field=models.CharField(default='reviewer', max_length=13),
        ),
    ]
