# Generated by Django 4.2.7 on 2023-12-08 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ememo', '0008_remove_flowememo_assign_flowememo_step'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flowememo',
            old_name='step',
            new_name='moderator',
        ),
    ]
