# Generated by Django 4.2.7 on 2023-12-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ememo', '0009_rename_step_flowememo_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowememo',
            name='moderator',
            field=models.CharField(blank=True, default='reviewer', max_length=13, null=True),
        ),
    ]
