# Generated by Django 4.2.7 on 2023-12-21 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ememo', '0013_flowememo_can_reject_flowememo_can_revert'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmemoMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.ImageField(upload_to='files/ememo/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='ememo.ememo')),
            ],
        ),
    ]
