# Generated by Django 4.2.7 on 2023-12-21 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ememo', '0014_ememomedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ememo',
            name='file',
        ),
    ]
