# Generated by Django 4.2.7 on 2023-12-21 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ememo', '0015_remove_ememo_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ememomedia',
            old_name='product_inventory',
            new_name='ememo',
        ),
    ]
