# Generated by Django 4.2.7 on 2023-12-27 10:21

from django.db import migrations, models
import ememo.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ememo', '0017_log_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ememo',
            name='action',
        ),
        migrations.AlterField(
            model_name='ememomedia',
            name='file_url',
            field=models.FileField(blank=True, null=True, upload_to='files/ememo/', validators=[ememo.validators.validate_file_size]),
        ),
    ]
