# Generated by Django 4.2.7 on 2023-12-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ememo', '0018_remove_ememo_action_alter_ememomedia_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ememo',
            name='number',
            field=models.TextField(default=1000000, verbose_name='Number'),
            preserve_default=False,
        ),
    ]
