# Generated by Django 4.2.7 on 2023-12-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ememo', '0019_ememo_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ememo',
            name='number',
            field=models.IntegerField(verbose_name='Number'),
        ),
    ]
