version: '3.3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=tutorial
      - POSTGRES_PASSWORD=tutorial
      - POSTGRES_DB=tutorial
    ports:
      - "127.0.0.1:5433:5433"
    volumes:
        - pgdata:/var/lib/postgresql/data/

  web:
    build: .
    restart: unless-stopped
    # command: gunicorn backend.wsgi:application -w 4 -b 0.0.0.0:8000
    command: bash -c "python manage.py collectstatic --no-input && python manage.py makemigrations && python manage.py migrate && gunicorn --workers=3 backend.wsgi -b 0.0.0.0:8000"
    env_file:
      - .app.env
    ports:
       - 8000:8000
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      - db

  proxy:
    image: caddy:alpine
    restart: always
    volumes:
      - caddy-data:/data
      - caddy-config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
      - app-static:/var/www/django/static:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db
      - web

volumes:
  pgdata:
  caddy-data: {}
  caddy-config: {}
  app-static: {}