version: '3.3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=tutorial
      - POSTGRES_PASSWORD=tutorial
      - POSTGRES_DB=tutorial
    ports:
      - "127.0.0.1:5433:5433"
    volumes:
        - pgdata:/var/lib/postgresql/data/

  web:
    build: .
    restart: unless-stopped
    # command: gunicorn backend.wsgi:application -w 4 -b 0.0.0.0:8000
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn --workers=3 backend.wsgi -b 0.0.0.0:8000"
    env_file:
      - .env
    ports:
       - 8000:8000
    volumes:
       - ./static:/code/static
    links:
      - db
    depends_on:
      - db

  caddy:
    image: caddy:2.4.5-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy_data:/data
      - ./caddy_config:/config
      - ./static:/code/static
    depends_on:
      - db
      - web

volumes:
  pgdata:
  static:
