version: '3.3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=tutorial
      - POSTGRES_PASSWORD=tutorial
      - POSTGRES_DB=tutorial
    ports:
      - "127.0.0.1:5433:5433"
    volumes:
        - pgdata:/var/lib/postgresql/data/

  web:
    build: .
    restart: unless-stopped
    # command: gunicorn backend.wsgi:application -w 4 -b 0.0.0.0:8000
    command: bash -c "python manage.py collectstatic --no-input && python manage.py makemigrations && python manage.py migrate && gunicorn --workers=3 backend.wsgi -b 0.0.0.0:8000"
    env_file:
      - .app.env
    ports:
       - 8000:8000
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      - db

  caddy:
    image: abiosoft/caddy
    depends_on:
    - "web"
    restart: always
    environment:
      ACME_AGREE: "true"
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./Caddyfile:/etc/Caddyfile
    - caddy_certs:/root/.caddy
    - media:/code/media
    - static:/code/staticfiles

volumes:
  pgdata:
  media:
  static:
  caddy_certs: