# Generated by Django 4.2.7 on 2023-12-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customuser_fullname_alter_customuser_jobtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runnumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Form Name')),
                ('running_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Running Name')),
            ],
        ),
    ]
