# Generated by Django 4.2.7 on 2023-12-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_runnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runnumber',
            name='running_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Running Number'),
        ),
    ]
