# Generated by Django 4.2.7 on 2023-11-28 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='Note',
        ),
    ]
