# Generated by Django 4.2.7 on 2023-12-03 05:15

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_note_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficLight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', django_fsm.FSMField(default='green', max_length=50, protected=True)),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='state',
            field=django_fsm.FSMField(default='green', max_length=50, protected=True),
        ),
    ]
