# Generated by Django 4.2.7 on 2023-12-06 16:18

from django.db import migrations, models
import note.models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_trafficlight_note_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=note.models.file_generate_upload_path),
        ),
    ]
